name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_PREFIX: ${{ secrets.DOCKER_USERNAME }}/miniproject

jobs:

# ---------------- BUILD ----------------
  build:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.vars.outputs.tag }}

    steps:
      - uses: actions/checkout@v3

      - name: Set tag
        id: vars
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Images
        run: |
          TAG=${{ steps.vars.outputs.tag }}

          docker build -t $IMAGE_PREFIX-order:$TAG ./order_service
          docker build -t $IMAGE_PREFIX-tracking:$TAG ./tracking_service
          docker build -t $IMAGE_PREFIX-delivery:$TAG ./delivery_service

          docker push $IMAGE_PREFIX-order:$TAG
          docker push $IMAGE_PREFIX-tracking:$TAG
          docker push $IMAGE_PREFIX-delivery:$TAG


# ---------------- TEST ----------------
  test:
    runs-on: ubuntu-latest
    needs: build

    outputs:
      tag: ${{ needs.build.outputs.tag }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull image
        run: |
          TAG=${{ needs.build.outputs.tag }}
          docker pull $IMAGE_PREFIX-order:$TAG

      - name: Run container
        run: |
          TAG=${{ needs.build.outputs.tag }}

          docker run -d -p 5001:5001 $IMAGE_PREFIX-order:$TAG
          sleep 10

          curl -f http://localhost:5001 || exit 1


# ---------------- DEPLOY ----------------
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Output tag for deployment
        run: |
          echo "===================================="
          echo "✅ IMAGE TAG READY: ${{ needs.test.outputs.tag }}"
          echo "Run locally:"
          echo "./deploy.sh ${{ needs.test.outputs.tag }}"
          echo "===================================="